[package]
name = "chaincord"
version = "0.1.15"
description = "Decentralized live chat"
authors = ["chaincord"]
edition = "2021"
license = "Apache-2.0"

[lib]
name = "chaincord_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ed25519-dalek = { version = "2", features = ["rand_core"] }
rand = "0.8"
sha2 = "0.10"
hex = "0.4"
base64 = "0.22"
chacha20poly1305 = "0.10"
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.26", features = ["native-tls"] }
futures-util = "0.3"
local-ip-address = "0.6"
rusqlite = { version = "0.32", features = ["bundled"] }
ureq = { version = "2.12", default-features = false, features = ["native-tls"] }

[target.'cfg(windows)'.dependencies]
webview2-com = "0.38"

[target.'cfg(any(target_os = "linux", target_os = "dragonfly", target_os = "freebsd", target_os = "netbsd", target_os = "openbsd"))'.dependencies]
webkit2gtk = { version = "=2.0.2", features = ["v2_38"] }

[target.'cfg(target_os = "linux")'.dependencies]
bytes = "1"
gdk = "0.18"
image = { version = "0.25", default-features = false, features = ["jpeg"] }
openh264 = { version = "0.6.6", default-features = false, features = ["source"] }
webrtc = "0.17.2"

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-updater = "2"
tauri-plugin-process = "2"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
